name       : nix
version    : 2.12.0
release    : 2
source     :
    - https://github.com/NixOS/nix/archive/refs/tags/2.12.0.tar.gz : 1d9ce6a096c9df6d4840ead1d3c3efce9c7ec749c7493d946d9cb28c4084d864
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : The purely functional package manager 
description: |
    Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible.
patterns   : /*
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(libbrotlidec)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - pkgconfig(bdw-gc)
    - pkgconfig(libeditline)
    - pkgconfig(libseccomp)
    - pkgconfig(libcpuid)
    - pkgconfig(libarchive)
    - pkgconfig(lowdown)
    - pkgconfig(nlohmann_json)
    - autoconf-archive
    - bison-devel
    - flex-devel
    - gtest-devel
    - libboost-devel
    - lowdown
    - jq
setup      : |
    %reconfigure --enable-gc \
                 --localstatedir=/var/nix \
                 --disable-doc-gen \
build      : |
    %make
install    : |
    %make_install
