name       : nix
version    : 2.16.1
release    : 7
source     :
    - https://github.com/NixOS/nix/archive/refs/tags/2.16.1.tar.gz : dcea9d91faf5cbe4198a45bf4f4a325902bc7056d04fb44eefbcdf8b8fc46f18
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : The purely functional package manager
description: |
    Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible.
lto        : yes
avx2       : yes
patterns   : /*
# networking : yes # Required for full doc gen
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(libbrotlidec)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - pkgconfig(bdw-gc)
    - pkgconfig(libeditline)
    - pkgconfig(libseccomp)
    - pkgconfig(libcpuid)
    - pkgconfig(libarchive)
    - pkgconfig(lowdown)
    - pkgconfig(nlohmann_json)
    - autoconf-archive
    - busybox
    - bison-devel
    - flex-devel
    - libboost-devel
    - lowdown
    - jq
rundeps    :
    - busybox
setup      : |
    # # Enable later when we want to build documentation too.
    # sed -i 's|$(bindir)|$(nix_DIR)|g' doc/manual/local.mk

    %reconfigure --enable-gc \
                 --disable-doc-gen \
                 --disable-tests \
                 --localstatedir=/nix/var \
                 --with-sandbox-shell=/bin/busybox \
build      : |
    %make
install    : |
    %make_install

    # systemd integration
    install -Dm00644 $pkgfiles/tmpfiles.conf "$installdir/%libdir%/tmpfiles.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/sysusers.conf "$installdir/%libdir%/sysusers.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/user.tmpfiles.conf "$installdir/usr/share/user-tmpfiles.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/user.environment.conf "$installdir/%libdir%/environment.d/nix-daemon.conf"

    # configuration
    install -Dm00644 $pkgfiles/nix.conf -t "$installdir/etc/nix"

    # rm -rf \
    #     "$installdir/etc/init" \
    #     "$installdir/etc/profile.d/nix.sh" \
    #     "$installdir/etc/profile.d/nix.fish"
