name       : nix
version    : 2.19.2
release    : 11
source     :
    - https://github.com/NixOS/nix/archive/refs/tags/2.19.2.tar.gz : 8afa34cd67196ba087093ff8b39ab20c4c86b381c51eefa0ca352f239a455b40
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : The purely functional package manager
description: |
    Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible.
clang      : yes
lto        : yes
avx2       : yes
# networking : yes # Required for full doc gen
patterns   : /*
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(libbrotlidec)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - pkgconfig(bdw-gc)
    - pkgconfig(libeditline)
    - pkgconfig(libseccomp)
    - pkgconfig(libcpuid)
    - pkgconfig(libarchive)
    - pkgconfig(lowdown)
    - pkgconfig(nlohmann_json)
    - autoconf-archive
    - busybox
    - bison-devel
    - flex-devel
    - libboost-devel
    - lowdown
    - jq
rundeps    :
    - busybox
setup      : |
    # # Enable later when we want to build documentation too.
    # sed -i 's|$(bindir)|$(nix_DIR)|g' doc/manual/local.mk

    %reconfigure --enable-gc \
                 --disable-doc-gen \
                 --disable-tests \
                 --localstatedir=/nix/var \
                 --with-sandbox-shell=/usr/bin/busybox \
build      : |
    %make
install    : |
    %make_install

    # systemd integration
    install -Dm00644 $pkgfiles/tmpfiles.conf "$installdir/%libdir%/tmpfiles.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/sysusers.conf "$installdir/%libdir%/sysusers.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/user.tmpfiles.conf "$installdir/usr/share/user-tmpfiles.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/user.environment.conf "$installdir/%libdir%/environment.d/nix-daemon.conf"

    # configuration
    install -Dm00644 $pkgfiles/nix.conf -t "$installdir/etc/nix"

    # mv $installdir/usr/lib/** $installdir/%libdir%
    rm -rf \
        "$installdir/etc/init" \
        "$installdir/etc/profile.d" \
