name       : nix
version    : 2.14.0
release    : 6
source     :
    - https://github.com/NixOS/nix/archive/refs/tags/2.14.0.tar.gz : 7f95535f82d7bd5654714f9eea2dfa1ee4331a8c49be8df251e19fb307f5cf7f
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : The purely functional package manager
description: |
    Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible.
lto        : yes
avx2       : yes
patterns   : /*
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(libbrotlidec)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - pkgconfig(bdw-gc)
    - pkgconfig(libeditline)
    - pkgconfig(libseccomp)
    - pkgconfig(libcpuid)
    - pkgconfig(libarchive)
    - pkgconfig(lowdown)
    - pkgconfig(nlohmann_json)
    - autoconf-archive
    - busybox
    - bison-devel
    - flex-devel
    - gtest-devel
    - libboost-devel
    - lowdown
    - jq
rundeps    :
    - busybox
setup      : |
    %reconfigure --enable-gc \
                 --disable-doc-gen \
                 --localstatedir=/nix/var \
                 --with-sandbox-shell=/bin/busybox \
build      : |
    %make
install    : |
    %make_install

    # systemd integration
    install -Dm00644 $pkgfiles/tmpfiles.conf "$installdir/%libdir%/tmpfiles.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/sysusers.conf "$installdir/%libdir%/sysusers.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/user.tmpfiles.conf "$installdir/usr/share/user-tmpfiles.d/nix-daemon.conf"
    install -Dm00644 $pkgfiles/user.environment.conf "$installdir/%libdir%/environment.d/nix-daemon.conf"

    # configuration
    install -Dm00644 $pkgfiles/nix.conf -t "$installdir/etc/nix"

    # rm -rf \
    #     "$installdir/etc/init" \
    #     "$installdir/etc/profile.d/nix.sh" \
    #     "$installdir/etc/profile.d/nix.fish"
