name       : solidity
version    : 0.8.10
release    : 1
homepage   : https://soliditylang.org
source     :
    - https://github.com/ethereum/solidity/releases/download/v0.8.10/solidity_0.8.10.tar.gz : 3f157aa2bc8bcbd8975fe5e41c476b3d777432dfe7c64e9d59247ee225a89ee3
license    : GPL-3.0-or-later
component  : programming
summary    : Solidity, the smart contract programming language
description: |
    Solidity is a statically typed, contract-oriented, high-level language for implementing smart contracts on the Ethereum platform.
builddeps  :
    # - pkgconfig(cln) # cvc4 optional dependency for optimized build
    # - pkgconfig(gmp) # cvc4
        - pkgconfig(z3)
        - libboost-devel
    # - openjdk-11-devel # cvc4
    # - python-toml # cvc4
networking : yes
    # environment: |
    #     JAVA_HOME=/usr/lib64/openjdk-11
    #     export PATH=$JAVA_HOME/bin:$PATH
    # setup      : |
    #     # Install cvc4
    #     tar -xf $sources/1.8.tar.gz -C .
    #     cd cvc5-1.8 && mkdir build
    #     ./contrib/get-antlr-3.4 && ./contrib/get-glpk-cut-log
    #     ./configure.sh production --gpl --cln --glpk --prefix=/usr # Can't use the macro, this is the only option it takes...
    #     cd build
    #     %make
    #     make check # The installation instructions instructed to put tests here
    #     %make_install
build      : |
    %cmake_ninja -DUSE_CVC4=OFF
    %ninja_build
install    : |
    %ninja_install
