name       : editline
version    : 1.17.1
release    : 1
source     :
    - https://github.com/troglobit/editline/archive/refs/tags/1.17.1.tar.gz : d65c5739c8ca388fa71feabc5aae506d052e1a6d288ee4e7fcab7efb07a3be74
license    : Spencer-94 # Thanks Void Linux
component  : programming.library
summary    : A small replacement for GNU readline() for UNIX
description: |
    editline is a small line editing library. It can be linked into almost any program to provide command line editing and history functions. It is call compatible with the FSF readline library, but at a fraction of the size, and as a result fewer features.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
