name       : krita
version    : 5.0.2
release    : 78
source     :
    - https://invent.kde.org/graphics/krita/-/archive/v5.0.2/krita-v5.0.2.tar.gz : 40f1e9a449b658f3e23f228cda9ca00495b0effa976cc34c86eec00eb06d45b0
homepage   : https://krita.org
license    : GPL-3.0-or-later
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application
description: |
    Krita is a professional FREE and open source painting program. It is made by artists that want to see affordable art tools for everyone.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gsl)
    - pkgconfig(kseexpr)
    - pkgconfig(libheif)
    - pkgconfig(libmypaint)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(poppler-qt5)
    - pkgconfig(python3)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - giflib-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - python-sip
    - python3-qt5
    - quazip-devel
    - vc
rundeps    :
    - breeze
    - ffmpeg
    - python3-qt5
setup      : |
    %cmake -DBUILD_TESTING=OFF \
           -DENABLE_UPDATERS=OFF \
           -DBUILD_KRITA_QT_DESIGNER_PLUGINS=ON \
           -B build
build      : |
    %make -C build
install    : |
    %make_install -C build
    %qml_cache

    rm -rf $installdir/usr/share/applications/krita*.desktop
