name       : perl-uri-encode
version    : 1.1.1
release    : 1
source     :
    - https://cpan.metacpan.org/modules/by-module/URI/URI-Encode-v1.1.1.tar.gz : 4bb9ce4e7016c0138cf9c2375508595286efa1c8dc15b45baa4c47281c08243b
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Percent encoding/decoding for URIs
description: |
    Percent encoding/decoding for URIs
builddeps  :
    - perl-module-build
    - perl-encode
    - perl-test-needs
    - perl-business-isbn
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
