name       : flatbuffers
version    : 2.0.0
release    : 5
source     :
    - https://github.com/google/flatbuffers/archive/v2.0.0.tar.gz : 9ddb9031798f4f8754d00fca2f1a68ecf9d0f83dfac7239af1311e4fd9a565c4
license    : Apache-2.0
component  : programming.library
summary    : FlatBuffers is an efficient cross platform serialization library.
description: |
    FlatBuffers is an efficient cross platform serialization library for
    C++, C#, C, Go, Java, JavaScript, Lobster, Lua, TypeScript, PHP,
    Python, and Rust.

    It was originally created at Google for game development and other
    performance-critical applications.
builddeps  :
    - pkgconfig(valgrind)
setup      : |
    sed -i 's/-Werror=/-W/g;s/-Werror//g' CMakeLists.txt
    %cmake \
        -DFLATBUFFERS_CODE_SANITIZE=ON \
        -DFLATBUFFERS_ENABLE_PCH=ON \
        -DFLATBUFFERS_BUILD_SHAREDLIB=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
