name       : supabase-cli
version    : 1.38.2
release    : 3
source     :
    - https://github.com/supabase/cli/archive/refs/tags/v1.38.2.tar.gz : a245f64c7a6a9413e86f60990ea8e1bb01b3c168c544c818b284a327d5752edb
license    : MIT
component  : programming.tools
summary    : Supabase CLI
description: |
    CLI for Supabase, an open source Firebase alternative.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags '-s -w -X github.com/supabase/cli/cmd.version=%version%'
install    : |
    install -Dm00755 cli $installdir/usr/bin/supabase
