image: silkeh/solus:ypkg

include: '/.gitlab/ci/template.yml'

stages:
  - lint
  - build
  - deploy

.lint-test-job:
  stage: lint
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 1
    - echo "No lint issues found."

.deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

abi-wizard:
  extends: .build

cascadia-code:
  extends: .build

darts:
  extends: .build

glibmm-2.68:
  extends: .build

ibus-theme-tools:
  extends: .build

krita:
  extends: .build
  timeout: 5h

microsoft-edge:
  extends: .build

mold:
  extends: .build

netease-cloud-music-gtk:
  extends: .build

ossfs:
  extends: .build

rpi-imager:
  extends: .build

tangram:
  extends: .build

trezor-bridge:
  extends: .build

vala-language-server:
  extends: .build
