image: registry.gitlab.com/solus-grocery-store/solbuild:latest
# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - /var/lib/solbuild/
  script:
    - echo "Compiling the code..."
    - apk update && apk upgrade && apk add cifs-utils util-linux-misc
    - mount --version
    - solbuild init --debug -u
    - ls /var/lib
    - ls /var/lib/solbuild
    - cd mold && sudo solbuild build --debug && echo success || ls /var/cache/solbuild/main-x86_64/mold
    - echo "Compile complete."
    - ls /var/lib/solbuild
