name       : darts
version    : 0.32
release    : 1
source     :
    - http://chasen.org/~taku/software/darts/src/darts-0.32.tar.gz : 0dfc0b82f0a05d93b92acf849368e54bf93f1de8ffb31ba0a21e45ab9e269285
homepage   : http://chasen.org/~taku/software/darts/
license    :
    - BSD-3-Clause
    - LGPL-2.1-or-later
component  : programming.library
summary    : C++ template library for implementation of Double-Array
description: |
    C++ template library for implementation of Double-Array 
setup      : |
    %configure
build      : |
    %make
    %make check
install    : |
    %make_install
