name       : lapack
version    : 3.10.0
release    : 2
source     :
    - https://github.com/Reference-LAPACK/lapack/archive/refs/tags/v3.10.0.tar.gz : 328c1bea493a32cac5257d84157dc686cc3ab0b004e2bea22044e0a59f6f8a19
license    : BSD-3-Clause
summary    : Basic Linear Algebra Subprograms
description: |
    Basic Linear Algebra Subprograms
builddeps  :
    - gfortran
setup      : |
    # sed -e 's|/CMAKE/|/cmake/|' -i CBLAS/CMakeLists.txt
    # mkdir build && cd build
    %cmake -B build \
        -DBUILD_TESTING=OFF \
        -DCMAKE_Fortran_COMPILER=gfortran \
        -DLAPACKE=ON \
        -DCBLAS=ON \
        -DBUILD_DEPRECATED=ON \
        -DBUILD_SHARED_LIBS=ON
build      : |
    %make -C build
install    : |
    %make_install -C build

