name       : nlohmann-json
version    : 3.11.2
release    : 1
source     :
    - https://github.com/nlohmann/json/archive/refs/tags/v3.11.2.tar.gz : d69f9deb6a75e2580465c6c4c5111b89c4dc2fa94e3a85fcd2ffcd9a143d9273
license    : MIT
component  : programming.library
summary    : JSON for Modern C++
description: |
    JSON for Modern C++
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
