name       : solana
version    : 1.6.27
release    : 1
source     :
    - https://github.com/solana-labs/solana/archive/refs/tags/v1.7.13.tar.gz : e89af646d14bf5e7d1c8b36dd988b09b7d8b7d03bdbaeb7fdb5230ee6d530191
license    : Apache-2.0
component  : programming.tools
clang      : yes
networking : yes
summary    : Solana CLI tools.
description: |
    Web-Scale Blockchain for fast, secure, scalable, decentralized apps and marketplaces.
builddeps  :
    - pkgconfig(libssl)
    - rustup
    - llvm-clang
build      : |
    ./scripts/cargo-install-all.sh .
install    : |
    install -Dm0064 $installdir/usr/share/solana
    cp -R bin/* $installdir/usr/share/solana

    pushd $installdir/usr/share/solana
    find . -maxdepth 1 -type f -executable -exec ln -s /usr/share/solana/{} $installdir/usr/bin/{} \;
    popd
