name       : monero-gui
version    : 0.17.3.0
release    : 1
source     :
    - git|https://github.com/monero-project/monero-gui : v0.17.3.0
homepage   : https://getmonero.org
license    : BSD-3-Clause
component  : network.web
summary    : Monero GUI client.
description: |
    The Qt GUI client for Monero, based on the core Monero implementation.
builddeps  :
    - pkgconfig(hidapi-libusb)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(libgvc) # For graphviz
    - pkgconfig(libsodium)
    - pkgconfig(libunbound)
    - pkgconfig(libunwind)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libzmq)
    - pkgconfig(miniupnpc)
    - pkgconfig(openpgm-5.3)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Help) # For `lrelease` when dealing with internationalization
    - pkgconfig(Qt5MultimediaWidgets) # For optional camera scan QR-code module
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5QuickTemplates2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Xml)
    - pkgconfig(x11)
    - doxygen
    - libboost-devel
setup      : |
    %cmake_ninja -DWITH_SCANNER=ON
build      : |
    %ninja_build
install    : |
    install -Dm00755 build/bin/monero-wallet-gui -t $installdir/usr/bin

    install -Dm00644 $pkgfiles/monero-gui.desktop -t $installdir/usr/share/applications/

    for x in 16 24 32 48 64 96 128 256; do
      install -Dm00644 "images/appicons/${x}x${x}.png" "$installdir/usr/share/icons/hicolor/${x}x${x}/apps/monero-gui.png"
    done
