# Refactored from Arch AUR: https://aur.archlinux.org/packages/wechat-uos.
# All credits to the maintainers of `wechat-uos` on Arch AUR. Thank you so much
# for all of your work!
name       : wechat-uos
version    : 2.1.5
release    : 2
source     :
  - https://home-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.weixin/com.tencent.weixin_2.1.5_amd64.deb : bd537bc3ea0f5cd4cc27f835469c3f0152c8cad31723e80b89e36e75dcb22181
license    : Proprietary
component  : internet.im
summary    : Native WeChat in UOS
description: |
    Native WeChat in UOS
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(atspi-2)
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(cairo-gl)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libsecret-1)
    - pkgconfig(osmesa)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - cups-devel
rundeps    :
    - bubblewrap
install    : |
    install -dm00755 $installdir

    # Extract files
    tar -Jxf data.tar.xz -C $installdir
    install -dm00755 ${installdir}%libdir%/wechat-uos
    # Copy the app itself to /usr/share/wechat-uos
    mv $installdir/opt/apps/com.tencent.weixin/files/weixin $installdir/usr/share/wechat-uos
    rm -r $installdir/opt

    # Move /usr/lib/license/libuosdevicea.so to /usr/lib64/wechat-uos/
    mv $installdir/usr/lib/**/** ${installdir}%libdir%/wechat-uos
    chmod 0644 ${installdir}%libdir%/wechat-uos/libuosdevicea.so

    # Required for bubblewrap to bind directories correctly
    rm -rf $installdir/usr/lib && install -dm00755 ${installdir}%libdir%/license 

    # Some mysterious files from Arch that allows it to run...
    tar -xf $pkgfiles/license.tar.gz -C $installdir/usr/share/wechat-uos

    # Desktop file and launch script with bubblewrap
    rm $installdir/usr/share/applications/weixin.desktop
    install -Dm00644 $pkgfiles/wechat-uos.desktop $installdir/usr/share/applications/wechat-uos.desktop
    install -Dm00755 $pkgfiles/wechat.sh $installdir/usr/bin/wechat
