name       : python-polars
version    : 0.18.4
release    : 3
source     :
    - https://github.com/pola-rs/polars/archive/refs/tags/py-0.18.4.tar.gz : 1cf0f1ca348a7c0bbf53a9a3f967f57bd744541c0fd1f576b378041af98bd315
license    : MIT
component  : programming.python
summary    : Fast multi-threaded, hybrid-streaming DataFrame library
description: |
    Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow Columnar Format as the memory model.
builddeps  :
    - pkgconfig(jemalloc)
    - pkgconfig(libgit2)
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
    - python-maturin
    # - cargo
    - rustup
networking : yes
setup      : |
    # For SIMD optimizations, nightly Rust is required
    rustup toolchain install nightly
build      : |
    cd py-polars
    maturin build -j %YJOBS% --release --strip -- -C target-cpu=native
install    : |
    cd py-polars
    python3 -m pip install --no-deps --root=$installdir target/wheels/*.whl
