name       : tangram
version    : 1.4.2
release    : 3
source     :
    - git|https://github.com/sonnyp/Tangram.git : v1.4.2
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : Browser for your pinned tabs
homepage   : https://github.com/sonnyp/Tangram
description: |
    Tangram is a new kind of browser. It is designed to organize and run your Web applications. Each tab is persistent and independent. You can set multiple tabs with different accounts for the same application.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gjs-1.0)
    - desktop-file-utils
    - nodejs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
