name       : bazelisk
version    : 1.15.0
release    : 3
source     :
    - https://github.com/bazelbuild/bazelisk/archive/refs/tags/v1.15.0.tar.gz : 0105d0e77ffda5a54d908e8781c5ed5551cd2810291c7b7071308bf0b387e4c1
license    : Apache-2.0
component  : programming.tools
summary    : A user-friendly launcher for Bazel
description: |
    Bazelisk is a wrapper for Bazel written in Go. It automatically picks a good version of Bazel given your current working directory, downloads it from the official server (if required) and then transparently passes through all command-line arguments to the real Bazel binary. You can call it just like you would call Bazel.
networking : yes
conflicts  :
    - bazel
builddeps  :
    - golang
build      : |
    go build -ldflags="-s -w -X github.com/bazelbuild/bazelisk/core.BazeliskVersion=%version%"
install    : |
    install -Dm00755 bazelisk -t $installdir/usr/bin

    ln -s /usr/bin/bazelisk $installdir/usr/bin/bazel
