name       : cascadia-code
version    : 2111.01
release    : 2
source     :
    - https://github.com/microsoft/cascadia-code/releases/download/v2111.01/CascadiaCode-2111.01.zip : 51fd68176dffb87e2fbc79381aef7f5c9488b58918dee223cd7439b5aa14e712
license    : OFL-1.1-RFN
component  : desktop.font
summary    : A fun, new monospaced font by Microsoft that includes programming ligatures.
description: |
    Cascadia Code is a fun, new monospaced coding font that includes programming ligatures and is designed to enhance the modern look and feel of the Windows Terminal.
install    : |
    install -dm00644 $installdir/usr/share/fonts/truetype/cascadia-code
    cp -R ttf/** $installdir/usr/share/fonts/truetype/cascadia-code
