name       : abi-wizard
version    : 1.0.8
release    : 1
source     :
    - https://github.com/DataDrake/abi-wizard/archive/refs/tags/v1.0.8.tar.gz : 12659e99c121c7a23125f65484d46a566b645baafa4f56721034b315e00e4218
license    : Apache-2.0
component  : system.devel
summary    : Tool for generating ABI reports for libraries and binaries.
description: |
    Tool for generating ABI reports for libraries and binaries.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
