name       : eopkg4
version    : 4.0
release    : 4
source     :
    - git|https://github.com/getsolus/eopkg.git : 789d134212046ebf1a6ac80b9fdede0738808b9b
homepage   : https://github.com/getsolus/eopkg/tree/python3
license    : GPL-2.0-or-later
component  : system.utils
summary    : "Python3 port of eopkg/pisi (WARNING: for testing only)"
description: |
    Python3 port of eopkg/pisi. WARNING: this is for testing only and may break your system!
builddeps  :
    - python-build
    - python-wheel
    - python-packaging
    - python-installer
    - python-lxml
    - python-magic
setup      : |
    echo "import setuptools" >> setup.py
    echo "setuptools.setup()" >> setup.py
    %python3_setup
install    : |
    %python3_install

    for file in eopkg lseopkg uneopkg; do
        mv $installdir/usr/bin/$file $installdir/usr/bin/${file}4
    done
