name       : microsoft-edge
version    : 111.0.1661.62
release    : 14
source     :
    - https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_111.0.1661.62-1_amd64.deb : d7ed8232773fdf1e5a7cbd92f5ba19402d608a96c87bf1a28e58bc8005d72245
license    : Proprietary
component  : network.web.browser
summary    : The web browser from Microsoft.
extract    : no
description: |
    Microsoft Edge is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
builddeps  :
    # Why do we need these when we do not actually build the application?
    # Because eopkg will be able to auto-detect rundeps.
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(atspi-2)
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(cairo-gl)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libdrm)
    - pkgconfig(libsecret-1)
    - pkgconfig(osmesa)
    - pkgconfig(pango)
    - pkgconfig(Qt5Core)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - cups-devel
rundeps    :
    - gconf
    - libxscrnsaver
setup      : |
    ar x $sources/microsoft-edge-stable_${version}-1_amd64.deb
    tar xf data.tar.*
install    : |
    mkdir -p $installdir
    cp -r usr $installdir/
    cp -r opt/microsoft/msedge $installdir/usr/share/
    ln -s /usr/share/msedge/microsoft-edge $installdir/usr/bin/microsoft-edge
    install -Dm00644 opt/microsoft/msedge/product_logo_128.png $installdir/usr/share/pixmaps/microsoft-edge.png

    # Remove stuff that aren't necessary on Solus
    sed -i 's/microsoft-edge-stable/microsoft-edge/g' $installdir/usr/share/applications/microsoft-edge.desktop
    rm -f $installdir/usr/bin/microsoft-edge-stable
