name       : microsoft-edge
version    : 99.0.1150.36
release    : 6
source     :
    - https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_99.0.1150.36-1_amd64.deb : af645b4b7df7b48b9393e774b3d855a816cd4672fe403ec8caa0ba18352f77ce
license    : Proprietary
component  : network.web.browser
summary    : The web browser from Microsoft.
description: |
    Microsoft Edge is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
builddeps  :
    # Why do we need these when we do not actually build the application?
    # Because eopkg will be able to auto-detect rundeps.
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(atspi-2)
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(cairo-gl)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libdrm)
    - pkgconfig(libsecret-1)
    - pkgconfig(osmesa)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - cups-devel
rundeps    :
    - gconf
    - libxscrnsaver
setup      : |
    ar x $sources/microsoft-edge-stable_${version}-1_amd64.deb
    tar xf data.tar.*
install    : |-
    mkdir -p $installdir
    cp -r usr $installdir/
    cp -r opt/microsoft/msedge $installdir/usr/share/
    ln -sfn /usr/share/msedge/microsoft-edge $installdir/usr/bin/microsoft-edge
    install -Dm00644 opt/microsoft/msedge/product_logo_128.png $installdir/usr/share/pixmaps/microsoft-edge.png

    # Remove stuff that aren't necessary on Solus
    sed -i 's/microsoft-edge-stable/microsoft-edge/g' $installdir/usr/share/applications/microsoft-edge.desktop
    rm -f $installdir/usr/bin/microsoft-edge-stable
