name       : microsoft-edge
version    : 96.0.1054.53
release    : 3
source     :
    - https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_96.0.1054.53-1_amd64.deb : 5b74062683f768f01b06ddee1012c2a95bd60c0e7378687bf8e12deb6d646ac4
license    : Proprietary
component  : network.web.browser
summary    : The web browser from Microsoft.
description: |
    Microsoft Edge is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(xscrnsaver)
rundeps    :
    - gconf
    - libxscrnsaver
setup      : |
    ar x $sources/microsoft-edge-stable_${version}-1_amd64.deb
    tar xf data.tar.*
install    : |-
    mkdir -p $installdir
    cp -r usr $installdir/
    cp -r opt/microsoft/msedge $installdir/usr/share/
    ln -sfn /usr/share/msedge/microsoft-edge $installdir/usr/bin/microsoft-edge
    install -Dm00644 opt/microsoft/msedge/product_logo_128.png $installdir/usr/share/pixmaps/microsoft-edge.png

    # Remove stuff that aren't necessary on Solus
    sed -i 's/microsoft-edge-stable/microsoft-edge/g' $installdir/usr/share/applications/microsoft-edge.desktop
    rm -f $installdir/usr/bin/microsoft-edge-stable
