name       : mold
version    : 1.0.1
release    : 1
source     :
    - https://github.com/rui314/mold/archive/refs/tags/v1.0.1.tar.gz : b0d54602d1229c26583ee8a0132e53463c4d755f9dbc456475f388fd8a1aa3e4
license    : AGPL-3.0-or-later
component  : programming.tools
summary    : A modern linker.
description: |
    mold is a faster drop-in replacement for existing Unix linkers. mold is created for increasing developer productivity by reducing build time especially in rapid debug-edit-rebuild cycles.
clang      : yes
builddeps  :
    - pkgconfig(libxxhash)
    - intel-tbb-devel
    - mimalloc-devel # pkgconfig(mimalloc) should work, but it doesn't...
build      : |
    %make PREFIX=/usr LTO=1 SYSTEM_MIMALLOC=1 SYSTEM_TBB=1 SYSTEM_XXHASH=1
install    : |
    %make_install PREFIX=/usr LTO=1 SYSTEM_MIMALLOC=1 SYSTEM_TBB=1 SYSTEM_XXHASH=1
