name       : mold
version    : 1.1.0
release    : 3
source     :
    - https://github.com/rui314/mold/archive/refs/tags/v1.1.tar.gz : 2f04bb2cd58797258c4f5f6f29fd2667f8b6c6b2bc76c731fede526884ea9a0c
license    : AGPL-3.0-or-later
component  : programming.tools
summary    : A modern linker.
description: |
    mold is a faster drop-in replacement for existing Unix linkers. mold is created for increasing developer productivity by reducing build time especially in rapid debug-edit-rebuild cycles.
clang      : yes
builddeps  :
    # - pkgconfig(libxxhash)
    # - intel-tbb-devel
    - mimalloc-devel
build      : |
    %make LTO=1 SYSTEM_MIMALLOC=1
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir% SYSTEM_MIMALLOC=1
