name       : l-smash
version    : 2.14.5
release    : 1
source     :
    - https://github.com/l-smash/l-smash/archive/refs/tags/v2.14.5.tar.gz : e6f7c31de684f4b89ee27e5cd6262bf96f2a5b117ba938d2d606cf6220f05935
homepage   : https://github.com/l-smash/l-smash
license    : ISC
component  : programming.library
summary    : MP4 muxer and other tools
description: |
    MP4 muxer and other tools
avx2       : yes
lto        : yes
setup      : |
    ./configure --prefix=/usr --libdir=%libdir% \
      --enable-shared \
      --disable-static \
      --extra-cflags="$CFLAGS" \
      --extra-ldflags="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install
