name       : cf-tool
version    : 1.0.2
release    : 2
source     :
    - https://gitlab.com/GZGavinZhao/cf-tool/-/archive/v1.0.2/cf-tool-v1.0.2.tar.gz : 106c393f6dfea84eb248d6d30cf710bc0426dad382bc50499c64c07aad657eca
homepage   : https://gitlab.com/GZGavinZhao/cf-tool
license    : MIT
component  : programming.tools
summary    : Codeforces CLI (Submit, Parse, Test, etc.)
description: |
    Codeforces Tool is a command-line interface tool for Codeforces.
networking : yes
builddeps  :
    - golang
build      : |
    go build cf.go
install    : |
    install -Dm00755 cf -t $installdir/usr/bin
