name       : netease-cloud-music-gtk
version    : 2.3.1
release    : 8
source     :
    - https://github.com/gmg137/netease-cloud-music-gtk/archive/refs/tags/2.3.1.tar.gz : e520bc3bdebd0b9522fa26fdd5991de278947552d968b9c8217ff87305990039
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Netease Cloud Music (网易云音乐) Rust + GTK client.
description: |
    Linux 平台下基于 Rust + GTK 开发的网易云音乐播放器。
networking : yes
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(graphene-gobject-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-player-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(pango)
    - cargo
    - desktop-file-utils
setup      : |
    # cargo check -r # Generate cargo.lock
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
