name       : netease-cloud-music-gtk
version    : 2.5.0
release    : 10
source     :
    - https://github.com/gmg137/netease-cloud-music-gtk/archive/refs/tags/2.5.0.tar.gz : a0bc68ae3851e66922d96ae3b76701fd1991d699093a5923ae31c96db4a5adc3
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Netease Cloud Music (网易云音乐) Rust + GTK client.
description: |
    Linux 平台下基于 Rust + GTK 开发的网易云音乐播放器。
networking : yes
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gobject-2.0)
    - pkgconfig(graphene-gobject-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-player-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(pango)
    - rust-devel
    - desktop-file-utils
setup      : |
    # cargo check -r # Generate cargo.lock
    # https://github.com/gmg137/netease-cloud-music-gtk/commit/7fabdadb2ebdbb2dfd76afa9f7f01f0170fc4749
    sed -i 's|~0.7|=0.7.0|' Cargo.toml
    %meson_configure --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
