name       : glab
version    : 1.26.0
release    : 3
source     :
    - https://gitlab.com/gitlab-org/cli/-/archive/v1.26.0/cli-v1.26.0.tar.gz : af1820a7872d53c7119a23317d6c80497374ac9529fc2ab1ea8b1ca033a9b4da
license    : MIT
component  : system.utils # gitlab-cli uses this... But why?
summary    : A GitLab CLI tool bringing GitLab to your command line
description: |
    GLab is an open source GitLab CLI tool bringing GitLab to your terminal next to where you are already working with git and your code without switching between windows and browser tabs. Work with issues, merge requests, watch running pipelines directly from your CLI among other features. Inspired by gh, the official GitHub CLI tool.
networking : yes
builddeps  :
    - golang
build      : |
    go build -o glab -ldflags "-s -w -X main.version=%version%" ./cmd/glab

    # manpages
    go run cmd/gen-docs/docs.go --manpage --path ./

    # command-line completions
    for s in bash fish zsh; do
    	./glab completion -s $s > $s.completions
    done
install    : |
    install -Dm0755 glab -t $installdir/usr/bin/
    install -Dm0644 glab -t $installdir/usr/share/man/man1/

    install -Dm0644 bash.completions $installdir/usr/share/bash-completion/completions/glab
    install -Dm0644 fish.completions $installdir/usr/share/fish/vendor_completions.d/glab.fish
    install -Dm0644  zsh.completions $installdir/usr/share/zsh/site-functions/_glab
